"""Out-of-fold score generation for base agents."""

from __future__ import annotations

import logging
from typing import Dict, Optional

import numpy as np
import pandas as pd

from module.common.purged_cv import PurgedEmbargoKFold

log = logging.getLogger(__name__)


def _agent_fallback_score(cfg: Dict) -> float:
    kwargs = dict(cfg.get("kwargs") or {})
    try:
        return float(kwargs.get("neutral_score", 0.5))
    except Exception:
        return 0.5


def generate_oof_scores(
    X: pd.DataFrame,
    y: pd.Series,
    agents_config: Dict[str, Dict],
    n_splits: int = 3,
    random_seed: int = 42,
    sector_map: Optional[Dict[str, str]] = None,
    spy_prices: Optional[pd.Series] = None,
) -> Dict[str, pd.Series]:
    """Generates out-of-fold (OOF) scores for all base agents.

    Splits are performed at the **quarter** level so that every ticker
    belonging to the same snapshot date lands in the same fold. This prevents
    the leakage that would arise if tickers from the same quarter appeared
    simultaneously in both the train and validation sets.

    When ``sector_map`` and ``spy_prices`` are provided, OOF sector scores are
    also generated by fitting an independent :class:`SectorRotationAgent` on
    each training fold and predicting on the corresponding validation fold.
    This eliminates the look-ahead that would result from using full-training-set
    sector predictions as meta-learner inputs.

    Args:
        X (pd.DataFrame): Feature matrix with a multi-index of (ticker, date).
        y (pd.Series): Binary target aligned with X.
        agents_config (Dict[str, Dict]): Agent configuration from
            :func:`~module.steps.step_03_training.agent_config.build_agents_config`.
        n_splits (int): Number of time-series CV folds.
        random_seed (int): Random seed forwarded to each agent.
        sector_map (Optional[Dict[str, str]]): Mapping of ticker → sector used
            to generate OOF sector scores. If None, sector OOF is skipped.
        spy_prices (Optional[pd.Series]): Daily SPY prices used by the sector
            agent to determine sector outperformance. If None, the sector agent
            falls back to an absolute return threshold.

    Returns:
        Dict[str, pd.Series]: Mapping of ``{agent_name}_score`` →
            OOF score Series. Missing folds are filled with the configured
            agent fallback score (sector_score keeps 0.5 as neutral no-tilt).
            Also includes ``sector_score`` when ``sector_map`` is provided.
    """
    # ── Quarter-level split with purging + embargo ───────────────────────────
    dates = X.index.get_level_values("date")
    unique_dates = sorted(dates.unique())
    effective_splits = min(n_splits, len(unique_dates) - 1)
    if effective_splits < 2:
        log.warning(
            "[OOF] Only %d unique dates; cannot form %d temporal splits. "
            "OOF scores will use configured fallback values.",
            len(unique_dates), n_splits,
        )
        neutral = {
            f"{ag_name}_score": pd.Series(
                _agent_fallback_score(cfg),
                index=X.index,
                name=f"{ag_name}_score",
            )
            for ag_name, cfg in agents_config.items()
        }
        if sector_map is not None:
            neutral["sector_score"] = pd.Series(0.5, index=X.index, name="sector_score")
        return neutral

    splitter = PurgedEmbargoKFold(
        n_splits=effective_splits,
        purge_days=90,
        embargo_days=30,
        allow_future_train=False,
    )

    fold_masks = []
    for tr_idx, val_idx in splitter.split(dates):
        train_mask = np.zeros(len(X), dtype=bool)
        val_mask = np.zeros(len(X), dtype=bool)
        train_mask[tr_idx] = True
        val_mask[val_idx] = True
        fold_masks.append((train_mask, val_mask))

    oof: Dict[str, pd.Series] = {}

    # ── Base agents ───────────────────────────────────────────────────────────
    for ag_name, cfg in agents_config.items():
        score_col = f"{ag_name}_score"
        oof_vals  = pd.Series(np.nan, index=X.index, name=score_col)
        rule_signal_col = f"{ag_name}_rule_signal"
        rule_hits_col = f"{ag_name}_rule_hits"
        rule_conf_col = f"{ag_name}_rule_confidence"
        oof_rule_signal = pd.Series(np.nan, index=X.index, name=rule_signal_col)
        oof_rule_hits = pd.Series(np.nan, index=X.index, name=rule_hits_col)
        oof_rule_conf = pd.Series(np.nan, index=X.index, name=rule_conf_col)
        log.info(
            "  [OOF] %s: generating anti-leakage scores (%d quarter-level temporal splits)",
            ag_name, effective_splits,
        )

        for split_i, (train_mask, val_mask) in enumerate(fold_masks):
            X_tr  = X.loc[train_mask]
            X_val = X.loc[val_mask]
            y_tr  = y.loc[train_mask]

            agent  = cfg["cls"](**cfg["kwargs"], save_artifacts=False)
            fallback_score = getattr(agent, "_neutral_score", _agent_fallback_score(cfg))
            y_fit  = (1 - y_tr) if cfg.get("invert_y") else y_tr

            try:
                if cfg.get("sector_col"):
                    agent.fit(X_tr, y_fit, fold=0, sector_col=cfg["sector_col"])
                    if getattr(agent, "is_trained", False):
                        preds = agent.predict_score(X_val, cfg["sector_col"])
                    else:
                        preds = pd.Series(fallback_score, index=X_val.index, name=score_col)
                else:
                    agent.fit(X_tr, y_fit, fold=0)
                    if getattr(agent, "is_trained", False):
                        preds = agent.predict_score(X_val)
                    else:
                        preds = pd.Series(fallback_score, index=X_val.index, name=score_col)
            except Exception:
                log.warning(
                    "[OOF] %s fold %d failed — using fallback score %.2f",
                    ag_name,
                    split_i,
                    float(fallback_score),
                    exc_info=True,
                )
                preds = pd.Series(fallback_score, index=X_val.index, name=score_col)

            oof_vals.loc[val_mask] = preds.reindex(X_val.index).values

            if getattr(agent, "is_trained", False) and hasattr(agent, "get_last_rule_details"):
                try:
                    details = agent.get_last_rule_details()
                    rs = pd.to_numeric(pd.Series(details.get("rule_signal"), index=X_val.index), errors="coerce").fillna(0.0)
                    rh = pd.to_numeric(pd.Series(details.get("rule_hits"), index=X_val.index), errors="coerce").fillna(0.0)
                    rc = pd.to_numeric(pd.Series(details.get("rule_confidence"), index=X_val.index), errors="coerce").fillna(0.0)
                    oof_rule_signal.loc[val_mask] = rs.reindex(X_val.index).values
                    oof_rule_hits.loc[val_mask] = rh.reindex(X_val.index).values
                    oof_rule_conf.loc[val_mask] = rc.reindex(X_val.index).values
                except Exception:
                    # Keep OOF robust when an agent does not provide rule telemetry.
                    pass

        oof[score_col] = oof_vals.fillna(float(fallback_score))
        if not oof_rule_signal.isna().all():
            oof[rule_signal_col] = oof_rule_signal.fillna(0.0)
            oof[rule_hits_col] = oof_rule_hits.fillna(0.0)
            oof[rule_conf_col] = oof_rule_conf.fillna(0.0)

            # Validate OOF rule signal quality: log IC (Spearman) between rule
            # signal and actual outcome.  Positive IC confirms rules are
            # predictive out-of-fold; negative IC is a warning sign of
            # overfitting or inverted labelling.
            try:
                y_num = pd.to_numeric(y.reindex(oof_rule_signal.index), errors="coerce")
                sig_num = pd.to_numeric(oof_rule_signal, errors="coerce")
                valid_mask = y_num.notna() & sig_num.notna()
                n_valid = int(valid_mask.sum())
                if n_valid >= 30:
                    ic = float(y_num[valid_mask].corr(sig_num[valid_mask], method="spearman"))
                    log.info(
                        "  [OOF/RuleIC] %s: rule_signal Spearman IC=%.4f (n=%d) — %s",
                        ag_name, ic, n_valid,
                        "predictive ✓" if ic > 0.02 else ("weak/noise" if abs(ic) <= 0.02 else "inverted ⚠"),
                    )
                else:
                    log.debug("  [OOF/RuleIC] %s: not enough valid pairs for IC (%d)", ag_name, n_valid)
            except Exception:
                pass

    # ── Sector agent (OOF) ────────────────────────────────────────────────────
    if sector_map is not None:
        from module.agents.sector_rotation import SectorRotationAgent

        sector_oof = pd.Series(np.nan, index=X.index, name="sector_score")
        log.info(
            "  [OOF] sector_rotation: generating OOF sector scores (%d quarter-level splits)",
            effective_splits,
        )

        for split_i, (train_mask, val_mask) in enumerate(fold_masks):
            X_tr  = X.loc[train_mask]
            X_val = X.loc[val_mask]

            sector_agent = SectorRotationAgent(
                results_dir=".", random_seed=random_seed, save_artifacts=False
            )
            try:
                sector_agent.fit(X_tr, sector_map=sector_map, spy_prices=spy_prices, fold=split_i)
                if sector_agent.is_trained:
                    sector_scores_dict = sector_agent.predict_sector_scores(X_val, sector_map)
                    preds = sector_agent.map_to_tickers(X_val, sector_map, sector_scores_dict)
                else:
                    preds = pd.Series(0.5, index=X_val.index, name="sector_score")
            except Exception:
                log.warning("[OOF] sector_rotation fold %d failed — using score 0.5", split_i, exc_info=True)
                preds = pd.Series(0.5, index=X_val.index, name="sector_score")

            sector_oof.loc[val_mask] = preds.reindex(X_val.index).values

        oof["sector_score"] = sector_oof.fillna(0.5)

    rule_sig_cols = [c for c in oof.keys() if c.endswith("_rule_signal")]
    if rule_sig_cols:
        oof["rules_consensus_signal"] = pd.concat([oof[c] for c in rule_sig_cols], axis=1).mean(axis=1)
    rule_conf_cols = [c for c in oof.keys() if c.endswith("_rule_confidence")]
    if rule_conf_cols:
        oof["rules_consensus_confidence"] = pd.concat([oof[c] for c in rule_conf_cols], axis=1).mean(axis=1)

    return oof
