"""Out-of-fold score generation for base agents."""

from __future__ import annotations

import logging
from typing import Dict, Optional

import numpy as np
import pandas as pd

log = logging.getLogger(__name__)


def _agent_fallback_score(cfg: Dict) -> float:
    kwargs = dict(cfg.get("kwargs") or {})
    try:
        return float(kwargs.get("neutral_score", 0.5))
    except Exception:
        return 0.5


def generate_oof_scores(
    X: pd.DataFrame,
    y: pd.Series,
    agents_config: Dict[str, Dict],
    n_splits: int = 3,
    random_seed: int = 42,
    sector_map: Optional[Dict[str, str]] = None,
    spy_prices: Optional[pd.Series] = None,
) -> Dict[str, pd.Series]:
    """Generates out-of-fold (OOF) scores for all base agents.

    Splits are performed at the **quarter** level so that every ticker
    belonging to the same snapshot date lands in the same fold. This prevents
    the leakage that would arise if tickers from the same quarter appeared
    simultaneously in both the train and validation sets.

    When ``sector_map`` and ``spy_prices`` are provided, OOF sector scores are
    also generated by fitting an independent :class:`SectorRotationAgent` on
    each training fold and predicting on the corresponding validation fold.
    This eliminates the look-ahead that would result from using full-training-set
    sector predictions as meta-learner inputs.

    Args:
        X (pd.DataFrame): Feature matrix with a multi-index of (ticker, date).
        y (pd.Series): Binary target aligned with X.
        agents_config (Dict[str, Dict]): Agent configuration from
            :func:`~module.steps.step_03_training.agent_config.build_agents_config`.
        n_splits (int): Number of time-series CV folds.
        random_seed (int): Random seed forwarded to each agent.
        sector_map (Optional[Dict[str, str]]): Mapping of ticker → sector used
            to generate OOF sector scores. If None, sector OOF is skipped.
        spy_prices (Optional[pd.Series]): Daily SPY prices used by the sector
            agent to determine sector outperformance. If None, the sector agent
            falls back to an absolute return threshold.

    Returns:
        Dict[str, pd.Series]: Mapping of ``{agent_name}_score`` →
            OOF score Series. Missing folds are filled with the configured
            agent fallback score (sector_score keeps 0.5 as neutral no-tilt).
            Also includes ``sector_score`` when ``sector_map`` is provided.
    """
    from sklearn.model_selection import TimeSeriesSplit

    # ── Quarter-level split ───────────────────────────────────────────────────
    # Sort by date so TimeSeriesSplit always places earlier quarters in train.
    dates = X.index.get_level_values("date")
    unique_dates = sorted(dates.unique())

    effective_splits = min(n_splits, len(unique_dates) - 1)
    if effective_splits < 2:
        log.warning(
            "[OOF] Only %d unique dates; cannot form %d temporal splits. "
            "OOF scores will use configured fallback values.",
            len(unique_dates), n_splits,
        )
        neutral = {
            f"{ag_name}_score": pd.Series(
                _agent_fallback_score(cfg),
                index=X.index,
                name=f"{ag_name}_score",
            )
            for ag_name, cfg in agents_config.items()
        }
        if sector_map is not None:
            neutral["sector_score"] = pd.Series(0.5, index=X.index, name="sector_score")
        return neutral

    kf = TimeSeriesSplit(n_splits=effective_splits)
    date_indices = np.arange(len(unique_dates))

    # Pre-compute boolean masks for each fold (indexed on X)
    fold_masks: List[tuple] = []
    for date_tr_idx, date_val_idx in kf.split(date_indices):
        train_dates = {unique_dates[i] for i in date_tr_idx}
        val_dates = {unique_dates[i] for i in date_val_idx}
        train_mask = dates.isin(train_dates)
        val_mask = dates.isin(val_dates)
        fold_masks.append((train_mask, val_mask))

    oof: Dict[str, pd.Series] = {}

    # ── Base agents ───────────────────────────────────────────────────────────
    for ag_name, cfg in agents_config.items():
        score_col = f"{ag_name}_score"
        oof_vals  = pd.Series(np.nan, index=X.index, name=score_col)
        log.info(
            "  [OOF] %s: generating anti-leakage scores (%d quarter-level temporal splits)",
            ag_name, effective_splits,
        )

        for split_i, (train_mask, val_mask) in enumerate(fold_masks):
            X_tr  = X.loc[train_mask]
            X_val = X.loc[val_mask]
            y_tr  = y.loc[train_mask]

            agent  = cfg["cls"](**cfg["kwargs"], save_artifacts=False)
            fallback_score = getattr(agent, "_neutral_score", _agent_fallback_score(cfg))
            y_fit  = (1 - y_tr) if cfg.get("invert_y") else y_tr

            try:
                if cfg.get("sector_col"):
                    agent.fit(X_tr, y_fit, fold=0, sector_col=cfg["sector_col"])
                    if getattr(agent, "is_trained", False):
                        preds = agent.predict_score(X_val, cfg["sector_col"])
                    else:
                        preds = pd.Series(fallback_score, index=X_val.index, name=score_col)
                else:
                    agent.fit(X_tr, y_fit, fold=0)
                    if getattr(agent, "is_trained", False):
                        preds = agent.predict_score(X_val)
                    else:
                        preds = pd.Series(fallback_score, index=X_val.index, name=score_col)
            except Exception:
                log.warning(
                    "[OOF] %s fold %d failed — using fallback score %.2f",
                    ag_name,
                    split_i,
                    float(fallback_score),
                    exc_info=True,
                )
                preds = pd.Series(fallback_score, index=X_val.index, name=score_col)

            oof_vals.loc[val_mask] = preds.reindex(X_val.index).values

        oof[score_col] = oof_vals.fillna(float(fallback_score))

    # ── Sector agent (OOF) ────────────────────────────────────────────────────
    if sector_map is not None:
        from module.agents.sector_rotation import SectorRotationAgent

        sector_oof = pd.Series(np.nan, index=X.index, name="sector_score")
        log.info(
            "  [OOF] sector_rotation: generating OOF sector scores (%d quarter-level splits)",
            effective_splits,
        )

        for split_i, (train_mask, val_mask) in enumerate(fold_masks):
            X_tr  = X.loc[train_mask]
            X_val = X.loc[val_mask]

            sector_agent = SectorRotationAgent(
                results_dir=".", random_seed=random_seed, save_artifacts=False
            )
            try:
                sector_agent.fit(X_tr, sector_map=sector_map, spy_prices=spy_prices, fold=split_i)
                if sector_agent.is_trained:
                    sector_scores_dict = sector_agent.predict_sector_scores(X_val, sector_map)
                    preds = sector_agent.map_to_tickers(X_val, sector_map, sector_scores_dict)
                else:
                    preds = pd.Series(0.5, index=X_val.index, name="sector_score")
            except Exception:
                log.warning("[OOF] sector_rotation fold %d failed — using score 0.5", split_i, exc_info=True)
                preds = pd.Series(0.5, index=X_val.index, name="sector_score")

            sector_oof.loc[val_mask] = preds.reindex(X_val.index).values

        oof["sector_score"] = sector_oof.fillna(0.5)

    return oof
